services:
    svd_media.alias.manager_service:    "@doctrine"

    svd_media.repository.file:
        arguments:
            -                           Svd\MediaBundle\Entity\File
        calls:
            -                           [setTranslator, ["@translator"]]
        class:                          Svd\MediaBundle\Entity\Repository\FileRepository
        factory:
            -                           "@svd_media.alias.manager_service"
            -                           getRepository
