services:
    gedmo.listener.softdeleteable:
        class:                          Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            -
                name:                   doctrine.event_subscriber
                connection:             default

    svd_media.form_type.media:
        calls:
            -                           [setIdToFileTransformer, ["@svd_media.transformer.id_to_file"]]
        class:                          Svd\MediaBundle\Form\Type\MediaType
        tags:
            -
                name:                   form.type
                alias:                  media

    svd_media.listener.upload:
        class:                          Svd\MediaBundle\EventListener\UploadListener
        tags:
            -
                name:                   doctrine.event_listener
                event:                  onFlush
            -
                name:                   doctrine.event_listener
                event:                  preSoftDelete

    svd_media.manager.file:
        calls:
            -                           [setRemoteFilesystem, ["@knp_gaufrette.filesystem_map", "%svd_media.adapter%"]]
            -                           [setFileRepository, ["@svd_media.repository.file"]]
        class:                          Svd\MediaBundle\Manager\FileManager

    svd_media.manager.media_url:
        arguments:
            -                           "%svd_media.base_url%"
            -                           "%svd_media.liip_imagine.filter_mapper%"
        calls:
            -                           [setLiipImagineCacheManager, ["@=service('service_container').has('liip_imagine.cache.manager')? service('liip_imagine.cache.manager') : null"]]
        class:                          Svd\MediaBundle\Manager\MediaUrlManager

    svd_media.transformer.id_to_file:
        calls:
            -                           [setFileRepository, ["@svd_media.repository.file"]]
            -                           [setMediaUrlExtension, ["@svd_media.twig_extension.media_url"]]
        class:                          Svd\MediaBundle\Form\DataTransformer\IdToFileTransformer

    svd_media.twig_extension.media_url:
        calls:
            -                           [setMediaUrlManager, ["@svd_media.manager.media_url"]]
        class:                          Svd\MediaBundle\Twig\MediaUrlExtension
        public:                         false
        tags:
            -
                name:                   twig.extension

    svd_media.validator.image:
        calls:
            -                           [setMediaUrlExtension, ["@svd_media.twig_extension.media_url"]]
        class:                          Svd\MediaBundle\Validator\Constraints\ImageValidator
        tags:
            -
                name:                   validator.constraint_validator
                alias:                  svdmedia_image_validator
