services:
    gedmo.listener.softdeleteable:
        class:                          Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
            -
                name:                   doctrine.event_subscriber
                connection:             default

    svd_media.form_type.media:
        calls:
            -                           [setIdToFileTransformer, [@svd_media.transformer.id_to_file]]
        class:                          Svd\MediaBundle\Form\Type\MediaType
        tags:
            -
                name:                   form.type
                alias:                  media

    svd_media.listener.upload:
        calls:
            -                           [setMediaManager, [@svd_media.manager.media]]
        class:                          Svd\MediaBundle\EventListener\UploadListener
        tags:
            -
                name:                   doctrine.event_listener
                event:                  onFlush
            -
                name:                   doctrine.event_listener
                event:                  preSoftDelete

    svd_media.manager.file:
        calls:
            -                           [setEntityManager, [@doctrine.orm.entity_manager]]
            -                           [setMediaManager, [@svd_media.manager.media]]
        class:                          Svd\MediaBundle\Manager\FileManager

    svd_media.manager.media:
        arguments:
            defaultTransformer:         default
        class:                          Svd\MediaBundle\Manager\MediaManager

    svd_media.transformer.id_to_file:
        calls:
            -                           [setFileRepository, [@svd_media.file.repository]]
            -                           [setMediaUrlExtension, [@svd_media.twig_extension.media_url]]
        class:                          Svd\MediaBundle\Form\DataTransformer\IdToFileTransformer

    svd_media.twig_extension.media_url:
        calls:
            -                           [setMediaBaseUrl, [%svd_media.base_url%]]
        class:                          Svd\MediaBundle\Twig\MediaUrlExtension
        public:                         false
        tags:
            -
                name:                   twig.extension

    svd_media.validator.image:
        class:                          Svd\MediaBundle\Validator\Constraints\ImageValidator
        calls:
            -                           [setMediaUrlExtension, [@svd_media.twig_extension.media_url]]
            -                           [setMediaManager, [@svd_media.manager.media]]
        tags:
            -
                name:                   validator.constraint_validator
                alias:                  svdmedia_image_validator
